// One source for the planning, projected lesson and generated course assets.
const times = ['19:00 - 19:45', '20:05 - 20:30', '20:30 - 20:50', '20:50 - 22:10'];
const blocks = [
  'Descobrir as colunas escondidas em telas conhecidas (streaming, loja e rede social), entender coluna, espaço entre colunas e margem, e experimentar a oficina de grade. Salvar o projeto antes do lanche.',
  'Montar individualmente a página da Arena Pixel, casa de games fictícia, numa grade de 12 colunas: cabeçalho, destaque, três cartões de campeonato e botão. Reconhecer componentes que se repetem. Exportar a versão 1.',
  'Atender ao pedido do cliente: incluir um quarto campeonato e reorganizar os cartões com a mesma largura, sem sair da grade. Testar a leitura e exportar a página final.',
  'Criar um post quadrado numa grade de 6 colunas. Personalizar com selo, texto, ícone e imagem; aplicar a mesma identidade na página e no post; testar a leitura com um colega. Salvar, reabrir e escrever uma frase sobre a grade. Encerrar às 22:10.'
];
export const planning = {
  title: 'Grades e Sistemas Visuais',
  description: 'Monte a página de uma casa de games numa grade de 12 colunas e crie um post da mesma família visual.',
  objectives: ['Desenvolvimento do Projeto: leiaute, templates e equilíbrio visual.'],
  technical: ['Aplicar procedimentos técnicos de diagramação, proximidade e alinhamento.', 'Aplicar estilos css (cascading style sheets) para desenvolvimento de design web.'],
  socio: ['Demonstrar espírito colaborativo em atividades coletivas.'],
  blocks, times,
  methodology: 'Descoberta visual com telas projetadas, jogo rápido de contagem de colunas, demonstração curta e produção individual em etapas na oficina de grade, com alteração de pedido do cliente e adaptação para post. Conferência automática da oficina e comparação com o colega do lado, cada um no seu posto.',
  resources: 'Computadores com navegador, projetor, caderno e caneta. Oficina de grade local e gratuita, sem instalação, cadastro ou dependências externas. Sem impressão e sem fichas. Baixar a oficina antes do encontro permite uso sem internet.',
  observation: '19:00–22:10, com lanche 19:45–20:05. Ritmo adaptado para a turma que chegou ao post às 20:50; os 40 minutos antecipados viram quatro desafios de composição. Manter as chamadas nos horários institucionais. Trabalho individual no posto; a colaboração acontece na conferência com o colega do lado, sem circulação. Se houver computador compartilhado, alternar o operador a cada etapa e manter uma frase por aluno. Sem internet: abrir a oficina previamente baixada. Sem computador: desenhar no caderno uma faixa de 12 colunas e montar a página e o post com retângulos, seguindo os mesmos critérios. A grade é trabalhada de forma visual; nenhum aluno escreve código. Câmeras e ring lights não são necessárias.'
};
export const lesson = {...planning, socioemotional: planning.socio, schedule: times.map((horario, i) => ({horario, atividade: blocks[i]}))};
delete lesson.blocks;
delete lesson.times;
delete lesson.socio;
export const visualAlt = {
  telas: 'Esboços de um streaming, de uma loja online e de uma rede social no celular',
  'telas-grade': 'Os mesmos esboços com as colunas marcadas em rosa: 12 colunas no streaming e na loja, 4 no celular',
  doze: 'Doze colunas divididas em 2 itens de 6, 3 de 4, 4 de 3 e 6 de 2',
  'pagina-inicial': 'Página da Arena Pixel com itens de larguras diferentes e desalinhados',
  'pagina-final-exemplo': 'Página da Arena Pixel com quatro cartões iguais encaixados na grade',
  'post-exemplo': 'Post quadrado da Arena Pixel com marca, destaque, cartão e botão na grade de 6 colunas'
};
const card = (title, text) => ({title, text});
const teacher = (speech, steps, watch, rescue = 'Se alguém travar, demonstrar um único movimento na oficina e devolver o controle ao aluno no posto.') => ({speech, steps, watch, rescue});
const slide = (title, block, lede, details, notes) => ({title, block, lede, layout: 'dw8', ...details, ...(details.visual ? {visualAlt: [details.visual].flat().map(name => visualAlt[name])} : {}), teacher: notes});
const editor = {href: 'modelos/design-web/aula-08/oficina.html', label: 'Abrir a oficina de grade'};
export const support = {
  appendDefaultClosing: false,
  teacherGoal: 'Cada estudante entrega a página da Arena Pixel na grade (versão 1 e final com quatro cartões iguais), o post quadrado da mesma família e o projeto editável reaberto até 22:10.',
  routine: ['Antes da aula, abrir a apresentação e baixar a oficina em cada computador; no computador da sala, exportar e abrir um PNG, salvar projeto.grade e reabri-lo nas duas abas.', 'Manter os alunos no posto; pedir atenção antes de cada demonstração e liberar só a etapa indicada.'],
  onlineRoutine: 'A oficina não usa serviços externos. Uma cópia baixada do HTML abre o mesmo recurso sem internet, por duplo clique.',
  plainLanguage: 'Grade é um conjunto de colunas invisíveis que organiza a tela. Componente é uma peça que se repete sempre igual, como um cartão ou um botão. Um conjunto de componentes que combinam forma um sistema visual, e é ele que faz peças diferentes parecerem da mesma marca.',
  say: 'Toda tela que vocês usam tem colunas escondidas. Hoje vamos encontrar essas colunas e usar uma grade para montar uma página e um post da mesma marca.',
  demo: ['Revelar as colunas em três telas conhecidas.', 'Arrastar um cartão na oficina e mostrar que ele gruda na coluna.', 'Mudar a largura de um cartão com Mais estreito e Mais largo.', 'Exportar um PNG, salvar e reabrir o projeto.'],
  studentDeliverable: 'Pasta Aula-08: pagina-v1.png, pagina-final.png, post-final.png e projeto.grade. Na etapa de personalização: pagina-alternativa.png e post-alternativa.png. No caderno, uma frase sobre o uso da grade. Alternativa: página e post desenhados no caderno sobre uma faixa de 12 colunas.',
  check: ['Todos os itens começam e terminam numa coluna.', 'Nada passa da margem; sobreposições decorativas são intencionais e não escondem informações.', 'Os quatro cartões da página final têm a mesma largura.', 'O post usa a mesma marca, o mesmo cartão e o mesmo botão da página.', 'Os PNGs das versões e o projeto editável foram salvos e reabertos.'],
  fallback: 'Abrir a cópia da oficina baixada antes da aula. Se o computador falhar, desenhar no caderno uma faixa de 12 colunas e montar a página com retângulos (cabeçalho, destaque, quatro cartões e botão); depois, um quadrado de 6 colunas para o post. Os critérios são os mesmos. Não distribuir fichas.',
  extension: 'Slides 19 a 22: quatro desafios de 40 minutos para a turma que concluiu o teste de leitura às 20:50. 21:18 selo, 21:28 imagem, 21:38 identidade e 21:50 teste com colega. Exportar pagina-alternativa.png e post-alternativa.png sem substituir os PNGs anteriores. Às 21:58, salvar e reabrir. Se houver atraso, reduzir a personalização e preservar os 12 minutos finais.',
  commonProblems: [
    ['O aluno quer trocar cor ou letra', 'Na primeira versão, priorizar posição e largura. Nos desafios de personalização, liberar cores e fontes, repetindo as escolhas na página e no post.'],
    ['O cartão novo fica maior para destacar', 'Perguntar se ele ainda parece irmão dos outros. No sistema, todo campeonato usa o mesmo cartão.'],
    ['Falta tempo', 'Priorizar a página final com quatro cartões e o post. Às 21:58, interromper a edição: 9 minutos para exportar, salvar, reabrir e organizar; 3 minutos para a frase e o encerramento.']
  ],
  presentationSlides: [
    slide('Mapa da noite', 1, 'Uma casa de games, uma grade de 12 colunas e duas peças da mesma família.', {cards: [card('Descobrir a grade', '19:00 às 19:45 · colunas escondidas em telas que você conhece.'), card('Montar a página', '20:05 às 20:30 · tudo encaixado na grade.'), card('Atender o cliente', '20:30 às 20:50 · um campeonato novo entra na página.'), card('Criar o post', '20:50 às 22:10 · mesma família, outro formato.')], promptLabel: 'Pausa', prompt: 'Lanche das 19:45 às 20:05. Encerramento às 22:10.'}, teacher('Primeiro organizamos as peças prontas na grade. Depois vamos personalizar cores, letras, imagens e formas mantendo a mesma identidade nas duas peças.', ['3 min · Fazer chamada e apresentar o produto da noite.', '2 min · Combinar posto fixo, voz baixa e mão levantada para pedir ajuda.'], 'Todos no próprio posto, sem formar grupos.')),
    slide('Tem uma grade escondida', 1, 'Três telas que você usa toda semana. Repare no que se repete.', {visual: 'telas', promptLabel: 'Observe', prompt: 'O que aparece várias vezes, sempre com o mesmo tamanho, em cada tela?'}, teacher('Não diga ainda que existe uma grade. Deixe a turma perceber a repetição sozinha.', ['1 min · Observar as três telas.', '1 min · Ouvir respostas: capas iguais, produtos iguais, posts iguais.', '1 min · Perguntar: por que alguém faria tudo do mesmo tamanho?'], 'Respostas que citam um elemento concreto: capa, produto, post, botão.')),
    slide('Agora com as colunas', 1, 'As faixas cor-de-rosa são colunas. Quase tudo começa e termina numa delas.', {visual: 'telas-grade', promptLabel: 'Desafio rápido', prompt: 'Quantas colunas ocupa uma capa do streaming? E um produto da loja?'}, teacher('Revele as colunas e peça que contem com o dedo, sem levantar.', ['1 min · Mostrar as colunas e dar tempo para contar.', '1 min · Ouvir palpites.', '2 min · Conferir: a capa do streaming ocupa 2 das 12 colunas; o produto da loja ocupa 3 das 12; o post do celular ocupa as 4 colunas.'], 'Resposta certa: 2 colunas para a capa e 3 para o produto. Vale explicação informal, desde que a contagem esteja certa.')),
    slide('As linhas invisíveis', 1, 'Grade é o esqueleto da tela: quem usa não vê, mas sente a organização.', {cards: [card('Coluna', 'Faixa onde os itens se apoiam. Um item pode ocupar uma ou várias.'), card('Espaço entre colunas', 'O respiro que impede um item de encostar no outro.'), card('Margem', 'A borda livre em volta da tela. Nada encosta nela.')], promptLabel: 'Resumo', prompt: 'Na grade, cada item começa numa coluna e termina numa coluna.'}, teacher('Aponte cada termo nas telas do slide anterior. Os nomes em português bastam; não é preciso termo técnico em inglês.', ['2 min · Explicar coluna e espaço entre colunas voltando às capas do streaming.', '1 min · Mostrar a margem da loja.', '1 min · Pedir que um aluno diga, do lugar, onde começa e onde termina um produto.'], 'A turma usa as palavras coluna, espaço e margem para descrever uma tela.')),
    slide('Por que 12 colunas?', 1, '12 se divide de vários jeitos. Por isso tantos sites usam essa grade.', {visual: 'doze', promptLabel: 'Pense rápido', prompt: 'Se a página tiver quatro cartões lado a lado, quantas colunas cada um ocupa?'}, teacher('Leia o slide como um jogo de divisão, sem conta no quadro.', ['1 min · Mostrar as quatro divisões.', '2 min · Ouvir a resposta do desafio: 3 colunas, porque 12 dividido por 4 dá 3.'], 'A resposta 3 volta mais tarde, quando o cliente pedir um cartão novo. Não antecipe esse pedido.')),
    slide('Experimente a oficina', 1, 'Abra a oficina da aula. Textos, cores e letras já estão prontos.', {cards: [card('1 · Crie a pasta', 'Crie uma pasta Aula-08 para guardar tudo de hoje.'), card('2 · Arraste um cartão', 'Com Mostrar colunas ligado, arraste um cartão. Ele gruda na coluna mais próxima.'), card('3 · Mude a largura', 'Use Mais estreito e Mais largo e veja quantas colunas o cartão ocupa.')], resources: [editor], promptLabel: 'Antes do lanche', prompt: 'Clique em Salvar projeto e guarde projeto.grade na pasta Aula-08.'}, teacher('Abra a oficina pelo link e mostre arrastar, mudar a largura, usar as setas e desfazer. Ninguém digita número nem código.', ['4 min · Às 19:19, demonstrar arrastar, mudar a largura e desfazer.', '15 min · Cada aluno experimenta com cartões; retomar coluna, espaço e margem enquanto circula o olhar pelos postos.', '7 min · Salvar projeto.grade, conferir o download na pasta Aula-08 e testar Abrir projeto.'], 'Onde o navegador guardou o arquivo. Resolva agora, não no fim da aula.', 'Se o link não abrir, usar a cópia baixada antes da aula. Sem computador, desenhar no caderno uma faixa com 12 colunas e marcar três cartões de 4 colunas.')),
    slide('Intervalo', 1, 'Lanche. Retome no mesmo posto às 20:05.', {pace: 'break', promptLabel: 'Antes de sair', prompt: 'Deixe o projeto salvo. Comida e bebida longe dos computadores.'}, teacher('O intervalo fica fora dos 170 minutos de atividade.', ['20 min · Intervalo das 19:45 às 20:05.'], 'Retomar sem reorganizar a sala.')),
    slide('O pedido da Arena Pixel', 2, 'Uma casa de games fictícia quer divulgar os campeonatos. A página chegou assim.', {visual: 'pagina-inicial', promptLabel: 'Missão individual', prompt: 'Coloque tudo na grade. Não mude textos nem cores: só posição e largura.'}, teacher('Faça a chamada. Pergunte o que está estranho antes de abrir a oficina.', ['2 min · Fazer chamada e retomar o projeto.', '2 min · Apresentar o pedido.', '1 min · Ouvir os problemas: cartões de larguras diferentes, começos desalinhados, cabeçalho e rodapé passando da margem.'], 'As críticas apontam o elemento, não quem fez a página.')),
    slide('Monte na grade', 2, 'Continue na oficina, na aba Página. Encaixe item por item.', {cards: [card('Topo', 'Cabeçalho e destaque ocupando a largura toda.'), card('Cartões', 'Os três lado a lado, com a mesma largura.'), card('Ação', 'Botão abaixo dos cartões, começando numa coluna.')], promptLabel: 'Conferência da oficina', prompt: 'O quadro Conferência marca ✓ quando está tudo na grade, dentro da margem, sem sobreposição e com cartões iguais lado a lado.'}, teacher('Demonstre só o cabeçalho. O resto é com eles.', ['2 min · Demonstrar o cabeçalho ocupando as 12 colunas.', '8 min · Montagem individual.', '1 min · Atender quem levantou a mão.'], 'Três cartões de 4 colunas é o caminho mais comum, mas outra solução que passe na conferência também vale.')),
    slide('Peças que se repetem', 2, 'Quando uma peça aparece sempre igual, ela vira componente.', {cards: [card('Cartão', 'Todo campeonato usa o mesmo cartão. Muda o texto, o desenho fica.'), card('Botão', 'Toda ação importante usa o mesmo botão.'), card('Cabeçalho', 'Toda página da Arena começa igual.')], promptLabel: 'Sistema visual', prompt: 'Componentes que combinam entre si formam um sistema visual. É ele que dá a várias peças a cara da mesma marca.'}, teacher('Volte às capas do streaming: cada capa é um componente repetido.', ['1 min · Explicar componente usando o cartão da oficina.', '1 min · Pedir exemplos de componentes em apps que a turma usa.', '1 min · Ligar componente e grade: o componente sempre ocupa colunas inteiras.'], 'Exemplos que a turma pode citar: botão de curtir, cartão de produto, miniatura de vídeo.')),
    slide('Versão 1', 2, 'Afaste-se um pouco da tela, sem levantar, e responda para você mesmo.', {bullets: ['Os três cartões parecem irmãos?', 'Os começos dos itens formam linhas retas?', 'O espaço entre os cartões é igual?'], promptLabel: 'Salve a versão 1', prompt: 'Com a conferência toda em ✓, escolha pagina-v1.png em Nome da imagem, clique em Exportar PNG e salve projeto.grade.'}, teacher('O teste é visual e rápido. Corrigir uma coisa e salvar.', ['2 min · Fazer o teste de olhar de longe.', '2 min · Corrigir um ponto.', '2 min · Exportar pagina-v1.png e salvar o projeto.'], 'Quem terminou cria uma alternativa com o botão em outra coluna, sem sair da grade.')),
    slide('Chegou um campeonato novo', 3, 'O cliente quer anunciar mais um campeonato na página.', {cards: [card('Novo cartão', 'Xadrez rápido · Sábado · 15h'), card('Condição', 'Os quatro cartões ficam lado a lado, com a mesma largura.'), card('Regra', 'Nada sai da grade nem das margens.')], promptLabel: 'Pedido do cliente', prompt: 'Clique em Incluir campeonato novo. Antes de mexer: quantas colunas cada cartão vai ocupar?'}, teacher('Faça a chamada e anuncie o pedido como se fosse o cliente.', ['2 min · Fazer chamada.', '2 min · Apresentar o pedido.', '1 min · Ouvir palpites. Resposta: 3 colunas cada, porque 12 dividido por 4 dá 3. É o desafio do início da aula.'], 'Quem lembrar do desafio das 12 colunas explica para a turma em uma frase.')),
    slide('Reorganize os cartões', 3, 'O cartão novo precisa caber na mesma linha, sem empurrar nada para fora.', {cards: [card('1 · Estreite', 'Deixe os três cartões antigos com 3 colunas.'), card('2 · Encaixe', 'Coloque o Xadrez rápido na mesma linha dos outros.'), card('3 · Confira', 'Veja se o botão e o rodapé continuam livres e na grade.')], promptLabel: 'Pronto quando', prompt: 'Quatro cartões iguais, lado a lado, e a conferência toda em ✓.'}, teacher('Mostre só como estreitar um cartão. Não monte a linha inteira.', ['2 min · Demonstrar Mais estreito em um cartão.', '6 min · Reorganização individual.', '1 min · Atender quem pedir ajuda.'], 'O cartão novo tem o mesmo desenho dos outros. Se alguém tentar deixá-lo maior para destacar, perguntar se ainda parece da mesma família.')),
    slide('Teste de leitura', 3, 'Olhe para a sua página sem apontar com o mouse.', {bullets: ['Qual campeonato acontece no sábado?', 'Onde eu clico para participar?', 'Algum cartão parece de outra família?'], promptLabel: 'Versão final da página', prompt: 'Corrija o que atrapalhou. Escolha pagina-final.png, exporte e salve projeto.grade.'}, teacher('Cada um testa a própria tela. O colega do lado pode responder do lugar dele, se quiser.', ['1 min · Fazer as três perguntas.', '2 min · Corrigir.', '3 min · Exportar pagina-final.png e salvar o projeto.'], 'O PNG final tem os quatro cartões.')),
    slide('Agora o post', 4, 'A Arena quer anunciar o xadrez no feed. O post precisa ter a cara da mesma marca.', {cards: [card('Mesma marca', 'O nome e o ícone da Arena no topo.'), card('Mesmo cartão', 'O Xadrez rápido com o mesmo desenho da página.'), card('Mesmo botão', 'Quero participar, igualzinho.')], promptLabel: 'Nova grade', prompt: 'Abra a aba Post quadrado. Aqui a grade tem 6 colunas.'}, teacher('Faça a chamada. Mostre que o formato mudou e a família não.', ['2 min · Fazer chamada.', '3 min · Apresentar o post.', '3 min · Abrir a aba e mostrar as 6 colunas.'], 'Primeiro preservar a identidade da página. Depois da comparação, os quatro desafios liberam personalização nas duas peças. Nesta turma, começar o post às 20:50.')),
    slide('Monte o post', 4, 'Os componentes são os mesmos. Só a grade mudou.', {cards: [card('1 · Topo', 'Marca no alto, começando na primeira coluna.'), card('2 · Meio', 'Destaque e cartão encaixados na grade de 6.'), card('3 · Ação', 'Botão perto do cartão, alinhado com ele.')], promptLabel: 'Pronto quando', prompt: 'Conferência em ✓. Escolha post-final.png, exporte e salve projeto.grade.'}, teacher('Demonstre só a marca. Deixe o resto com eles.', ['2 min · Demonstrar a marca na primeira coluna.', '12 min · Montagem individual do post.'], 'Botão e cartão lado a lado ou empilhados: os dois jeitos valem se estiverem na grade.')),
    slide('É da mesma família?', 4, 'Página e post lado a lado. Formatos diferentes, mesma marca.', {visual: ['pagina-final-exemplo', 'post-exemplo'], promptLabel: 'Compare com as suas', prompt: 'Mesmas cores, mesmo cartão, mesmo botão e tudo em colunas?'}, teacher('Mostre o exemplo só depois que a turma montou o próprio post.', ['2 min · Mostrar página e post lado a lado.', '4 min · Cada aluno compara as próprias peças e corrige um detalhe; o colega do lado dá um palpite, do lugar.'], 'O exemplo é uma solução possível, não a única resposta.')),
    slide('Crie um selo de destaque', 4, '10 minutos · Dê uma informação importante usando forma, texto e ícone.', {cards: [card('1 · Faça a base', 'Na aba Post quadrado, adicione uma Forma. Escolha retângulo ou círculo e uma cor de destaque.'), card('2 · Escreva por cima', 'Adicione Texto: “Inscrições abertas”. Use Trazer à frente para deixá-lo sobre a forma.'), card('3 · Dê significado', 'Adicione um Ícone, como troféu ou controle. Alinhe o conjunto sem cobrir o horário ou o botão.')], promptLabel: 'Pronto quando', prompt: 'O selo é legível, cabe nas margens e ajuda a entender o convite. Salve o projeto.'}, teacher('21:18–21:28. Demonstrar Forma, Texto e Ícone. Para selecionar algo coberto, usar Item selecionado. A conferência não avalia os elementos decorativos; conferir visualmente.', ['2 min · Demonstrar a base e as camadas em Posição, tamanho e camadas.', '6 min · Criar o selo e alinhar texto e ícone.', '2 min · Conferir se nada importante ficou escondido e salvar.'], 'Texto precisa caber inteiro. Se necessário, aumentar a altura ou reduzir Escala do texto. Não exigir agrupamento, pois a oficina não agrupa itens.', 'Usar apenas retângulo e texto. Desfazer recupera uma posição anterior.')),
    slide('Uma imagem que ajuda a comunicar', 4, '10 minutos · Escolha uma imagem do computador que combine com o campeonato.', {cards: [card('1 · Carregue', 'Adicione uma imagem PNG, JPG ou WebP que você já tenha. Escolha algo relacionado a jogos ou xadrez.'), card('2 · Enquadre', 'Compare Mostrar imagem inteira com Preencher e recortar. Ajuste largura e altura sem perder o assunto principal.'), card('3 · Organize', 'Reserve um espaço para a imagem. Se ela ficar atrás do texto, use uma forma de cor sólida para garantir a leitura.')], promptLabel: 'Compare antes e depois', prompt: 'A imagem ajuda a reconhecer o evento? O nome, o dia e o horário continuam fáceis de ler?'}, teacher('21:28–21:38. Usar arquivo já disponível, sem transformar a atividade em busca de imagens. Não há remoção de fundo nem edição de foto na oficina.', ['2 min · Mostrar carregamento e as duas opções de enquadramento.', '6 min · Inserir e ajustar a imagem na composição.', '2 min · Ocultar as colunas, conferir leitura e salvar.'], 'Não esticar rostos ou objetos nem cortar o assunto principal. Evitar imagem ocupando todo o espaço da informação.', 'Quem não tem imagem cria uma ilustração com duas formas e um ícone; o objetivo continua sendo comunicar o evento.')),
    slide('Sua versão da Arena Pixel', 4, '12 minutos · Personalize a campanha mantendo página e post na mesma família.', {cards: [card('Cores com função', 'Escolha até três cores principais: fundo, texto e destaque. Garanta contraste e repita as escolhas nas duas peças.'), card('Letras com hierarquia', 'Use até duas fontes. O nome do evento chama atenção; dia, horário e ação continuam claros.'), card('Peças que combinam', 'Repita cantos, cores e estilo dos cartões e botões. Preserve os quatro campeonatos na página.')], promptLabel: 'Guarde as duas versões', prompt: 'Exporte pagina-alternativa.png e post-alternativa.png. Preserve os PNGs anteriores e salve projeto.grade.'}, teacher('21:38–21:50. A identidade agora pode mudar, mas precisa mudar nas duas abas. Os controles editam o item selecionado; não existe aplicação automática de estilo em todos os itens.', ['2 min · Escolher as cores e fontes e anotar no caderno.', '7 min · Aplicar na página e no post, repetindo as escolhas nos componentes.', '3 min · Exportar as duas alternativas e salvar o projeto.'], 'Cor de destaque tem função; excesso de fontes não cria hierarquia. Se o texto não cabe, reduzir escala ou ampliar o bloco.', 'Manter a fonte atual e personalizar só uma cor de destaque nas duas peças.')),
    slide('O colega entendeu em cinco segundos?', 4, '8 minutos · Mostre o post sem explicar. O colega responde do próprio lugar.', {cards: [card('1 · Mostre e pergunte', 'Dê cinco segundos para olhar. Qual é o evento? Quando acontece? Como participar?'), card('2 · Ouça a evidência', 'Peça que aponte o que ficou difícil de encontrar. Depois troquem os papéis.'), card('3 · Melhore uma coisa', 'Ajuste tamanho, contraste, espaço ou posição. Testem de novo e exportem as alternativas atualizadas.')], promptLabel: 'Conclua com uma decisão', prompt: '“Mudei ___ porque meu colega não encontrou ___.” Às 21:58, pare a edição e confira os arquivos.'}, teacher('21:50–21:58. A conversa é breve, com o colega do lado, sem circulação. Avaliar compreensão, não gosto pessoal. Não exigir que a conferência automática julgue imagens e decorações.', ['2 min · Um aluno mostra e o outro responde; inverter os papéis.', '4 min · Cada aluno faz uma correção baseada no teste.', '2 min · Reexportar pagina-alternativa.png e post-alternativa.png e salvar.'], 'Uma mudança explicada por um problema de leitura vale mais que muitos enfeites.', 'Sem colega disponível, esconder a peça por alguns segundos e fazer o teste individualmente; o professor pode conferir do posto.')),
    slide('Salve e reabra', 4, '21:58: pare a edição. Agora é hora de salvar e conferir os arquivos.', {cards: [card('1 · Imagens', 'Versões iniciais e finais; mais pagina-alternativa.png e post-alternativa.png.'), card('2 · Projeto', 'Salvar projeto → projeto.grade.'), card('3 · Teste', 'Abra um PNG. Depois use Abrir projeto e confira a página e o post.')], promptLabel: 'Pasta Aula-08', prompt: 'Confira os cinco PNGs e projeto.grade na pasta Aula-08.'}, teacher('O navegador pode colocar números nos nomes repetidos. Guarde a versão mais recente.', ['4 min · Às 21:58, parar a edição, exportar o que faltar e salvar o projeto.', '4 min · Abrir um PNG e reabrir projeto.grade, conferindo as duas abas.', '1 min · Organizar a pasta Aula-08.'], 'PNG é só imagem: sem projeto.grade não dá para continuar editando.', 'Se o download falhar, tentar de novo e olhar a pasta Downloads. Persistindo, tirar captura de tela e escrever a conclusão no caderno; não considerar o projeto entregue sem conferir o arquivo.')),
    slide('Uma frase de designer', 4, 'No caderno, complete a frase com algo que você fez hoje.', {promptLabel: 'Sua frase', prompt: '“Usei a grade para ___ e isso ajudou ___.”', bullets: ['Exemplo: “Usei a grade para deixar os quatro cartões com a mesma largura e isso ajudou a comparar os horários.”', 'Pasta salva e posto organizado antes de sair.']}, teacher('Ouça duas frases e feche retomando grade, componente e sistema visual.', ['1 min · Escrever a frase no caderno.', '1 min · Ouvir duas respostas.', '1 min · Organizar os postos e encerrar às 22:10.'], 'Sem apresentações longas no encerramento.'))
  ]
};
