// One source for the planning, projected lesson and generated course assets.
const times = ['19:00 - 19:45', '20:05 - 20:50', '20:50 - 21:30', '21:30 - 22:10'];
const blocks = [
  'Comparar duas páginas de manutenção industrial, compreender margem, proximidade e alinhamento e experimentar o editor visual local. Salvar o ponto de partida.',
  'Organizar individualmente a página da empresa fictícia Eixo Manutenção: aproximar informações relacionadas, separar assuntos e repetir um eixo de alinhamento. Salvar a primeira versão.',
  'Atender à alteração do cliente: incluir atendimento aos sábados sem perder o agrupamento dos horários. Testar a leitura, revisar espaços e salvar uma segunda versão.',
  'Conferir a página por tarefas de leitura, corrigir o que ainda dificulta o uso, exportar e reabrir os arquivos. Justificar uma melhoria e encerrar às 22:10.'
];
export const planning = {
  title: 'Espaço, Proximidade e Alinhamento',
  description: 'Organize uma página de serviços industriais para que o cliente encontre o serviço, o horário e o próximo passo.',
  objectives: ['Desenvolvimento do Projeto: equilíbrio visual e leiaute.'],
  technical: ['Aplicar procedimentos técnicos de diagramação, proximidade e alinhamento.'],
  socio: ['Demonstrar no desenvolvimento das atividades sob a sua responsabilidade os princípios de profissionalismo.'],
  blocks, times,
  methodology: 'Diagnóstico projetado, demonstração visual, edição individual em etapas, alteração de pedido e conferência por critérios. Todos permanecem no posto; respostas coletivas por sinal e falas breves.',
  resources: 'Computadores com navegador, projetor, quadro, caderno e caneta. Editor visual local gratuito, sem instalação, cadastro ou dependências externas. Sem impressão e sem fichas de preenchimento. Exemplo e editor disponíveis no material da aula; baixar o editor antes do encontro permite uso sem internet.',
  observation: '19:00–22:10, com lanche 19:45–20:05. Chamada às 19:00, 20:05, 20:50 e 21:30. Trabalho individual no posto, sem circulação para revisão. Se houver computador compartilhado, alternar o operador a cada etapa e manter uma justificativa por aluno. Sem internet: abrir o editor HTML previamente baixado. Sem computador: desenhar antes e depois no caderno a partir da projeção, com os mesmos critérios. Sem projetor: usar o exemplo do editor nos computadores ou desenhar o modelo no quadro. Câmeras e ring lights não são necessárias nesta aula de diagramação.'
};
export const lesson = { ...planning, socioemotional: planning.socio, schedule: times.map((horario, i) => ({ horario, atividade: blocks[i] })) };
delete lesson.blocks;
delete lesson.times;
delete lesson.socio;
const card = (title, text, eyebrow) => ({ title, text, ...(eyebrow ? { eyebrow } : {}) });
const teacher = (speech, steps, watch, rescue = 'Se houver dificuldade, demonstrar uma única mudança e retomar a prática no posto.') => ({ speech, steps, watch, rescue });
const slide = (title, block, lede, details, notes) => ({title, block, lede, layout: 'dw7', ...details, teacher: notes});
const editor = {href:'modelos/design-web/aula-07/editor.html', label:'Abrir editor da Aula 07'};
export const support = {
  appendDefaultClosing: false,
  teacherGoal: 'Uma página de serviço reorganizada por estudante, com evidência inicial, projeto editável e PNG final reaberto até 22:10.',
  routine: ['Antes da aula, abrir a apresentação e baixar o editor em cada computador; testar uma exportação e a reabertura.', 'Manter alunos no posto; solicitar atenção antes da demonstração e liberar somente a etapa indicada.'],
  onlineRoutine: 'O editor não usa serviços externos. Baixar uma cópia do HTML permite abrir o mesmo recurso sem internet, por duplo clique.',
  plainLanguage: 'Proximidade mostra o que pertence ao mesmo assunto. Alinhamento cria uma referência para os olhos. Espaço separa assuntos e protege a leitura.',
  say: 'O cliente quer encontrar um serviço e solicitar um orçamento. Vamos organizar as informações para facilitar essas duas ações.',
  demo: ['Comparar a página inicial e o exemplo organizado.', 'Mover um título e aproximar o texto correspondente.', 'Ativar as margens e alinhar o início dos grupos.', 'Salvar, exportar e reabrir um arquivo.'],
  studentDeliverable: 'Pasta Aula-07: layout-inicial.png, layout-v1.png, layout-final.png e projeto.layout. No caderno, uma frase explicando a alteração e seu efeito na leitura. Alternativa: duas composições no caderno com o mesmo conteúdo e critérios.',
  check: ['Serviço, atendimento e botão estão presentes e legíveis.', 'Título e detalhe de cada assunto estão próximos; assuntos diferentes têm mais espaço.', 'Os grupos seguem um eixo de alinhamento consistente.', 'As margens estão livres; não há corte ou sobreposição.', 'O atendimento aos sábados aparece junto dos demais horários.', 'O PNG final e o projeto editável foram reabertos.'],
  fallback: 'Abrir a cópia do editor baixada antes da aula. Se o computador falhar, desenhar a composição inicial e a final no caderno a partir dos exemplos projetados; preservar os mesmos textos, alteração de sábado, agrupamento, eixo e margens. Não distribuir fichas.',
  extension: 'Depois de salvar a entrega, produzir uma segunda composição com os mesmos textos e critérios. Comparar qual permite localizar o horário mais rapidamente e justificar. Permanecer no posto até o encerramento.',
  commonProblems: [['O aluno altera a aparência e não a organização', 'Fixar as cores e fontes do editor; pedir que mova primeiro o detalhe para perto do título correspondente.'], ['O aluno termina cedo', 'Pedir uma alternativa de composição e comparação por tarefa; salvar a entrega essencial antes.'], ['Falta tempo', 'Priorizar os três grupos, o horário de sábado e os arquivos. Reservar os últimos 15 minutos para exportação e conferência.']],
  presentationSlides: [
    slide('Mapa da noite',1,'Uma página, um pedido realista e uma revisão com critérios.',{cards:[card('Observar e experimentar','19:00–19:45 · leitura visual e primeiro uso.'),card('Organizar a página','20:05–20:50 · produzir e salvar a versão 1.'),card('Atender à mudança','20:50–21:30 · incluir um novo horário.'),card('Conferir e entregar','21:30–22:10 · revisar, salvar e explicar.')],promptLabel:'Pausa',prompt:'Lanche das 19:45 às 20:05. Encerramento às 22:10.'},teacher('Hoje a cor e a fonte já estão definidas. Nosso trabalho é organizar informação.', ['3 min · Fazer chamada, apresentar o produto e situar o lanche.', '2 min · Combinar posto fixo, voz baixa e mão levantada para ajuda.'], 'Sem deslocamentos para formar grupos.')),
    slide('O pedido da Eixo Manutenção',1,'Uma empresa fictícia precisa de uma página de serviços para clientes de uma fábrica.',{cards:[card('Encontrar o serviço','Manutenção preventiva de máquinas.'),card('Conferir o atendimento','Segunda a sexta, das 8h às 18h.'),card('Dar o próximo passo','Solicitar orçamento.')],promptLabel:'Missão individual',prompt:'Organize a página com os textos fornecidos. Preserve o conteúdo e trabalhe no seu posto.'},teacher('Leia o pedido. Não é preciso inventar uma empresa nem pesquisar fotos. A composição é um estudo visual: o botão não envia solicitações.', ['3 min · Ler as três necessidades e relacionar ao trabalho de comunicação para indústria.', '2 min · Pedir que indiquem, por sinal, qual informação procurariam primeiro.'], 'Sem pesquisa paralela ou atividade de programação.')),
    slide('Onde está o horário?',1,'Observe em silêncio. Encontre o serviço, o horário e o botão.',{visual:'before',promptLabel:'Observe',prompt:'Qual informação parece pertencer ao grupo errado? Responda citando a posição.'},teacher('Mostre apenas a página inicial. Pergunte onde está o horário, sem antecipar a solução.', ['2 min · Dar tempo de leitura silenciosa.', '3 min · Ouvir três respostas breves.', '2 min · Nomear a dificuldade: distância entre título e detalhe.'], 'A resposta deve citar um elemento, não um julgamento sobre quem criou.')),
    slide('O conteúdo é o mesmo',1,'A posição muda a leitura: serviço com seu detalhe, atendimento com seu horário.',{visual:'after',promptLabel:'Compare',prompt:'Localize os mesmos três itens. O que ficou mais fácil de encontrar?'},teacher('A comparação mantém cores, fontes e conteúdo. Mudamos a distribuição dos elementos.', ['2 min · Mostrar a composição organizada.', '2 min · Retomar as três buscas.', '2 min · Relacionar cada ganho a uma mudança de posição.'], 'Não apresentar a composição como única resposta correta.')),
    slide('Três decisões de diagramação',1,'Organizar é mostrar o que está junto, o que é diferente e por onde começar.',{cards:[card('Proximidade','Título e detalhe do mesmo assunto ficam perto.'),card('Alinhamento','Os inícios dos grupos seguem a mesma linha.'),card('Espaço','A distância entre assuntos é maior que dentro de cada grupo.')],promptLabel:'Critério',prompt:'Centralizar tudo não garante organização. Escolha um eixo e repita-o.'},teacher('Aponte os exemplos na página anterior. O eixo é uma referência visual, não uma regra de que todo layout precisa ficar à esquerda.', ['3 min · Explicar proximidade usando Atendimento e seu horário.', '3 min · Mostrar o eixo comum.', '2 min · Comparar espaço interno e espaço entre assuntos.'], 'Evitar teoria sem apontar onde ela aparece.')),
    slide('Experimente uma mudança',1,'Abra o editor da aula. Os textos e a aparência já estão preparados.',{cards:[card('1 · Guarde o início','Clique em Exportar PNG e salve como layout-inicial.png.'),card('2 · Mova um item','Selecione o horário e arraste para perto de Atendimento.'),card('3 · Ajuste com precisão','Use as setas do teclado. Ative Mostrar margens para conferir as bordas.')],resources:[editor],promptLabel:'Antes do lanche',prompt:'Salve projeto.layout em uma pasta Aula-07. Aguarde no posto após concluir.'},teacher('Abra o editor pelo link. Demonstre seleção, arraste, setas, desfazer e salvar. Os números de posição são medidas visuais, não programação.', ['4 min · Demonstrar exportação inicial e movimento de um texto.', '3 min · Cada estudante experimenta mover e desfazer.', '5 min · Conferir download do PNG e do projeto na pasta Aula-07.', '2 min · Orientar a pausa sem fechar o arquivo.'], 'Conferir onde o navegador guardou os downloads. A capa e a navegação não acrescentam tempo.', 'Se o link não abrir, usar o HTML baixado. Sem computador, copiar o exemplo inicial no caderno e marcar a mudança.')),
    slide('Intervalo',1,'Lanche. Retome no mesmo posto às 20:05.',{pace:'break',promptLabel:'Antes de sair',prompt:'Deixe o projeto salvo. Guarde alimentos e bebidas longe dos computadores.'},teacher('O intervalo fica fora dos 170 minutos de atividade.', ['20 min · Intervalo das 19:45 às 20:05.'], 'Retomar sem reorganizar a sala.')),
    slide('Organize por assunto',2,'A página terá três grupos claros: apresentação, serviço e atendimento.',{cards:[card('Apresentação','EIXO MANUTENÇÃO + Soluções para sua produção.'),card('Serviço','Manutenção preventiva + Inspeção e ajustes de máquinas.'),card('Atendimento','Atendimento + Seg–sex · 8h às 18h.')],promptLabel:'Próximo passo',prompt:'Mantenha “Solicitar orçamento” visível depois das informações. Preserve “Empresa fictícia · exercício de diagramação”.'},teacher('Faça a chamada. Mostre um único par e deixe a turma organizar os demais.', ['2 min · Fazer chamada e retomar o projeto.', '3 min · Demonstrar a aproximação de um título e detalhe.', '10 min · Organizar os três pares individualmente.'], 'Detalhe precisa estar mais próximo de seu título que do próximo assunto.')),
    slide('Crie um eixo de leitura',2,'Ative as margens. Escolha onde os grupos começam e repita essa posição.',{cards:[card('1 · Alinhe os inícios','Use as guias ou o campo Posição horizontal para repetir a mesma medida.'),card('2 · Separe assuntos','Deixe uma distância maior entre os grupos.'),card('3 · Preserve as bordas','Mantenha textos e botão dentro das margens tracejadas.')],promptLabel:'Conferência',prompt:'As palavras não se sobrepõem. A margem não encosta nas letras. O botão cabe inteiro.'},teacher('Demonstre duas linhas com a mesma posição horizontal. Usar 48 é uma possibilidade, não resposta obrigatória. Não pedir que todos copiem as coordenadas do modelo.', ['3 min · Demonstrar o campo de posição e as guias.', '10 min · Ajustar os eixos e espaços.', '5 min · Conferir os alunos que sinalizaram dificuldade.'], 'Observar se alinhar virou encostar tudo: manter os espaços entre grupos.')),
    slide('Leia como um cliente',2,'Afaste-se um pouco da tela, permanecendo sentado. Procure os três itens.',{bullets:['Qual serviço é oferecido?','Quando a empresa atende?','Onde solicitar orçamento?'],promptLabel:'Versão 1',prompt:'Corrija um ponto que atrasou a leitura. Selecione layout-v1.png em Nome da imagem, exporte e salve projeto.layout.'},teacher('O aluno testa a própria tela. Se necessário, o vizinho observa do próprio lugar e responde sem tocar no projeto; isso é opcional.', ['3 min · Orientar as três buscas.', '5 min · Corrigir uma dificuldade concreta.', '4 min · Exportar versão 1 e salvar o projeto.'], 'Quem concluiu cria uma alternativa de posição mantendo o conteúdo; ninguém precisa circular.')),
    slide('O cliente mudou um detalhe',3,'A empresa também atenderá aos sábados. A página precisa mostrar isso com clareza.',{cards:[card('Novo conteúdo','Sábado · 8h às 12h'),card('Lugar adequado','Perto do horário de segunda a sexta.'),card('Condição','Preserve todos os textos, as margens e o botão.')],promptLabel:'Alteração solicitada',prompt:'Clique em Incluir sábado no editor. Organize a nova linha junto do atendimento.'},teacher('Faça chamada e apresente a mudança só agora. O objetivo é testar a organização quando o conteúdo cresce.', ['2 min · Fazer chamada.', '3 min · Apresentar o novo horário.', '3 min · Demonstrar a inclusão sem resolver a composição.'], 'O botão Incluir sábado acrescenta só uma linha.')),
    slide('Reorganize sem perder a leitura',3,'O horário novo precisa caber no mesmo assunto, sem se misturar ao botão.',{cards:[card('1 · Aproxime','Coloque sábado perto de Seg–sex.'),card('2 · Abra espaço','Desloque o botão se ele estiver perto demais dos horários.'),card('3 · Revise o conjunto','Confira o eixo, as margens e a separação entre assuntos.')],promptLabel:'Pronto quando',prompt:'Os dois horários formam um grupo e o botão continua inteiro, separado e legível.'},teacher('Faça uma demonstração breve de deslocar o botão para criar espaço. Não reduza o tamanho da letra para resolver tudo.', ['3 min · Mostrar a relação entre conteúdo novo e espaço disponível.', '12 min · Realizar a alteração individual.', '5 min · Conferir o atendimento em cada posto que solicitar apoio.'], 'Se faltar espaço, redistribuir grupos. O exemplo já mostra que o conteúdo cabe.')),
    slide('Teste de leitura do atendimento',3,'Olhe para a sua composição sem apontar com o mouse.',{bullets:['O sábado é encontrado junto dos outros dias?','Está claro onde o atendimento termina e onde começa a ação?','Há uma linha comum organizando os grupos?'],promptLabel:'Salve a revisão',prompt:'Ajuste uma distância e salve projeto.layout. Quem terminou cria uma segunda organização para comparar.'},teacher('Peça respostas individuais no próprio projeto. Ouça duas justificativas, sem apresentações na frente da sala.', ['3 min · Fazer o teste de leitura.', '6 min · Corrigir e salvar.', '3 min · Ouvir duas justificativas relacionadas a proximidade.'], 'Manter a turma no posto.')),
    slide('Conferência de qualidade',4,'Confira um critério por vez na sua página.',{cards:[card('Conteúdo completo','Serviço, dois horários, botão e identificação do exercício.'),card('Grupos claros','Título perto do detalhe; assuntos diferentes separados.'),card('Eixo consistente','Os inícios dos grupos seguem a mesma referência.'),card('Acabamento legível','Sem cortes, sobreposição ou elementos nas margens.')],promptLabel:'Ação',prompt:'Corrija primeiro o que impede a leitura. Depois refine as distâncias.'},teacher('Faça chamada. Peça que apontem os critérios na própria tela. A conferência é do produto, não uma ficha para preencher.', ['2 min · Fazer chamada.', '3 min · Ler os quatro critérios e demonstrar um erro de sobreposição.', '7 min · Cada estudante confere e identifica o ajuste principal.'], 'O PNG final deve conter o sábado.')),
    slide('Último ajuste',4,'Finalize o problema identificado na conferência.',{bullets:['Mantenha todos os textos do pedido.','Revise a distância do detalhe para seu título.','Confira se o espaço entre assuntos é maior.'],promptLabel:'Se a página já atende aos critérios',prompt:'Compare sua alternativa com a versão principal. Escolha a que facilita encontrar o horário e explique por quê.'},teacher('Reserve os últimos 15 minutos para arquivos e fechamento. Não abra uma nova atividade obrigatória.', ['8 min · Corrigir a página ou comparar uma alternativa.', '5 min · Conferir os casos que precisam de apoio antes de exportar.'], 'Às 21:55 iniciar o salvamento, mesmo se a alternativa estiver incompleta.')),
    slide('Salve e reabra',4,'A entrega precisa abrir fora do editor e permitir continuar a edição.',{cards:[card('1 · Imagem final','Nome da imagem: layout-final.png → Exportar PNG.'),card('2 · Projeto editável','Salvar projeto → projeto.layout.'),card('3 · Teste os arquivos','Abra o PNG. Depois use Abrir projeto para reabrir o arquivo salvo.')],promptLabel:'Pasta Aula-07',prompt:'layout-inicial.png + layout-v1.png + layout-final.png + projeto.layout'},teacher('O navegador pode acrescentar números aos nomes. Guarde a versão mais recente como projeto.layout. Peça salvamento antes da reabertura.', ['3 min · Exportar o PNG final e salvar projeto.', '4 min · Reabrir os dois arquivos e conferir o sábado.', '2 min · Organizar os quatro arquivos na pasta Aula-07.'], 'PNG não permite editar os elementos: o projeto é indispensável.', 'Se o download falhar, tentar novamente e verificar a pasta Downloads. Persistindo, registrar captura de tela e conclusão no caderno; não afirmar que o editável foi entregue.')),
    slide('A mudança que fez diferença',4,'No caderno, complete uma frase com uma mudança que você realizou.',{promptLabel:'Sua justificativa',prompt:'“Aproximei / alinhei / afastei ___ para facilitar ___.”',bullets:['Exemplo: “Aproximei o sábado dos outros dias para facilitar a leitura do atendimento.”','Mantenha a pasta salva e deixe o posto organizado.']},teacher('A frase não é ficha. Ouça duas respostas curtas e encerre às 22:10. Retome os três conceitos usando as mudanças citadas.', ['2 min · Registrar a frase no caderno.', '2 min · Ouvir duas respostas.', '2 min · Organizar os postos e encerrar às 22:10.'], 'Não solicitar apresentações longas ou tarefas extras no encerramento.'))
  ]
};
