// Fonte da aula e das notas; regenerar com node scripts/build-design-web-11.mjs.
const workshop = {href: 'https://oficinas-design-web.vercel.app/aula-11/', label: 'Abrir a oficina de interações'};
const creator = {href: 'https://oficinas-design-web.vercel.app/aula-11/criador.html', label: 'Abrir o criador de fluxos'};
const rescue = 'Demonstro uma ação no projetor e devolvo o controle ao estudante. Sem arquivo anterior, uso o exemplo pronto.';
const slide = (title, block, minutes, lede, cards, prompt, speech, steps, extra = {}) => ({
  title, block, layout: 'dw8', lede, cards: cards.map(([title, text]) => ({title, text})),
  promptLabel: 'Sua vez', prompt,
  teacher: {speech, steps: [`${minutes} min · ${steps}`], watch: 'Observo se a resposta informa o que aconteceu e permite continuar sem ajuda.', rescue}, ...extra
});
export const lesson = {
  title: 'Interações e Feedback da Interface',
  description: 'A Arena Pixel responde ao visitante. Os seis desafios de mensagem viram aquecimento; depois cada estudante cria, testa e adapta um fluxo clicável próprio para uma situação de atendimento.',
  objectives: ['Criação de código de texto: introdução ao Javascript como reconhecimento de bastidor.', 'Inovação: conceito, inovação x melhoria.'],
  technical: ['Identificar possibilidades de atualizações e melhorias de projetos web.', 'Aplicar conceitos de design de experiência e interação do usuário.'],
  socioemotional: ['Aplicar os aspectos de inovação em suas atividades profissionais.'],
  schedule: [
    {horario: '19:00 - 19:45', atividade: 'Comparar uma interface sem resposta com outra que orienta. Identificar ação, resposta e próximo passo; testar inscrição, erro e cancelamento. Registrar três problemas e salvar a versão inicial antes do lanche.'},
    {horario: '20:05 - 20:30', atividade: 'Retomar e concluir os seis desafios de mensagem como aquecimento. Quem já concluiu não repete: salva e prepara a troca para a nova oficina.'},
    {horario: '20:30 - 21:15', atividade: 'Criar um fluxo clicável individual a partir de um briefing: escolher uma situação, construir cinco telas conectadas e testar o caminho principal. Depois responder a uma mudança de requisito criando uma alternativa.'},
    {horario: '21:15 - 22:10', atividade: 'Fechar o teste com o colega; dar aparência ao aplicativo; criar um formulário ligado; simular carregamento e falha; fazer um speedrun, salvar e organizar o posto.'}
  ],
  methodology: 'Aquecimento curto de mensagens, prototipação visual individual por briefing, teste silencioso com o colega e revisão baseada no percurso observado.',
  resources: 'Computador com navegador, projetor, oficina de interações e criador de fluxos na Vercel, com cópias locais para uso sem rede. Caderno e caneta como alternativa. Sem login, instalação ou impressão.',
  observation: '19:00–22:10, intervalo 19:45–20:05. Os seis desafios são aquecimento e não geram nova contagem. Às 20:30 a turma abre o criador de fluxos. Trabalho individual no posto, com colaboração do colega do lado. Situações simuladas, sem dados pessoais ou envio pela rede; o estudante decide telas, rotas e respostas visuais.'
};
export const support = {
  appendDefaultClosing: false,
  teacherGoal: 'Cada estudante usa os seis desafios como aquecimento e, a partir de 20:30, cria um fluxo clicável próprio, adapta-o a um novo requisito, testa com o colega, cria uma tela de formulário e uma recuperação de falha e exporta uma versão que funciona fora do editor.',
  routine: ['Antes da aula, abro a oficina pública e o criador de fluxos no computador da sala; mantenho as cópias locais como alternativa sem rede.', 'Faço chamada no início dos quatro blocos; cada estudante trabalha no próprio posto e troca apenas com o colega ao lado.', 'Até 20:30, os seis desafios já feitos valem como aquecimento: não pedir repetição, nova frase ou novo contador. No slide 12 anuncio a troca; no slide 13 todos abrem o criador.', 'De 20:30 a 21:15, projeto cinco telas e uma mudança de requisito. Às 21:20, a turma abre diretamente o slide 16: aparência, formulário, falha e speedrun substituem a repetição do teste entre colegas. Das 22:05 às 22:10, apenas organização.', 'Não transformar o teste em relatório: somente observação oral curta. Quem termina cedo reduz cliques no speedrun e torna a recuperação de falha útil, sem criar decoração solta.'],
  onlineRoutine: 'Abro https://oficinas-design-web.vercel.app/aula-11/ para o aquecimento e, às 20:30, https://oficinas-design-web.vercel.app/aula-11/criador.html. O fluxo exportado funciona offline.',
  plainLanguage: 'Feedback é a resposta da tela: recebi seu toque, estou trabalhando, deu certo ou algo precisa mudar. Cor sozinha não conta a história.',
  say: 'Quando você aperta um botão e nada muda, toca de novo? Hoje vamos desenhar respostas que tiram essa dúvida.',
  demo: ['Comparo Sem resposta e Com resposta na oficina.', 'Às 20:30 escolho um briefing no criador, ligo Início → Escolha → Revisão → Concluído e testo.', 'Revelo que uma opção ficou indisponível, crio uma tela de alternativa distinta da Ajuda e testo as duas saídas.', 'No slide 16, escolho aparência, ligo o formulário na tela Início e simulo uma falha no Criador; depois exporto para percorrer a espera e o caminho normal com teclado.'],
  studentDeliverable: 'Pasta Aula-11 com `meu-fluxo.fluxo` e `meu-prototipo.html` do criador. O fluxo tem cinco telas conectadas, uma sexta tela de alternativa criada após a mudança de requisito e um teste com colega. As seis mensagens anteriores permanecem como aquecimento, sem nova entrega.',
  check: ['Briefing escolhido: reserva de estúdio, empréstimo de equipamento ou pedido de lanche.', 'Cinco telas editadas e conectadas: início, escolha, revisão, concluído e ajuda.', 'Caminho principal chega ao resultado e nenhuma tela usada fica sem saída.', 'A mudança de requisito cria uma sexta tela de alternativa; a outra opção continua funcionando.', 'Tema, nome e raio dão uma aparência coerente ao aplicativo.', 'Um formulário obrigatório mostra erro na própria tela quando vazio e leva a resposta para a mensagem seguinte.', 'No Criador, uma falha simulada chega à tela Erro e o botão Tentar de novo volta à Revisão; Cancelar espera mantém a pessoa na tela. A rota pode usar a sétima tela.', 'Arquivo do fluxo reabre editável; o protótipo exportado funciona sem rede e por teclado, com espera e caminho normal.'],
  fallback: 'Sem internet, abro a cópia local do criador. Sem computador, cada estudante desenha no caderno cinco caixas — início, escolha, revisão, concluído e ajuda — liga-as com setas e acrescenta uma sexta caixa de alternativa após a mudança de requisito. O colega percorre as setas sem receber dicas.',
  extension: 'Quem chegar ao critério entra no speedrun e tenta resolver o próprio fluxo em até oito cliques. Compara o percurso antes/depois, reduz uma rota desnecessária ou melhora a recuperação de falha; não volta a editar as seis mensagens. O Criador comporta de cinco a oito telas: seis para alternativa, sete para erro e a oitava só se ajudar.',
  commonProblems: [
    ['Aluno terminou os seis desafios e quer parar', 'No slide 13, abre o criador, escolhe um briefing e começa as cinco telas. Os desafios não precisam ser refeitos.'],
    ['Teste não revelou dificuldade', 'Peço que o colega escolha a rota sem pistas e observo apenas onde a pessoa hesita. Não mando inventar problema.'],
    ['Mensagem diz apenas “Erro”', 'Peço problema + orientação: “Escolha um campeonato para continuar”.'],
    ['O estudante acha que fez uma reserva real', 'Aponto o aviso de simulação; nenhuma vaga, equipamento ou pedido real é enviado.'],
    ['O colega recebe instruções durante o teste', 'Peço silêncio a quem criou a tela e observo onde a pessoa hesita.'],
    ['O navegador não guarda o rascunho', 'Uso Salvar rascunho e reabro `meu-fluxo.fluxo`; o rascunho não substitui a entrega.']
  ],
  presentationSlides: [
    slide('A tela precisa responder', 1, 5, 'Você tocou. Aconteceu alguma coisa?', [['Hoje', 'Uma inscrição fictícia na Arena Pixel.'], ['Entrega', 'Um protótipo que conversa com quem usa.']], 'Conte uma situação em que você tocou duas vezes por falta de resposta.', 'Faço a chamada e ouço dois exemplos. Retomo a página e o botão da Arena Pixel.', 'Chamada, dois relatos e apresentação da entrega.'),
    slide('O mesmo toque, duas experiências', 1, 10, 'Abra a oficina. Compare os dois botões da demonstração.', [['Sem resposta', 'Toque e observe a dúvida.'], ['Com resposta', 'Toque e acompanhe o que muda.']], 'Qual versão evita que você toque de novo? O que ela mostra?', 'Confiro: a segunda responde imediatamente, informa a espera e depois o resultado. Explico que JavaScript pode realizar essas respostas; hoje a turma toma as decisões de design.', 'Demonstro os dois botões, libero a comparação e confiro as respostas.', {resources: [workshop]}),
    slide('Ação → resposta → próximo passo', 1, 8, 'Uma boa resposta reduz a dúvida e mostra como continuar.', [['Ação', 'Enviar uma inscrição.'], ['Resposta', 'Enviando sua inscrição…'], ['Próximo passo', 'Inscrição confirmada. Veja o campeonato escolhido.']], 'Se falhar, o que precisa aparecer no lugar de “Não deu”?', 'Confiro: explicar o problema sem culpar e oferecer uma ação possível. Não prometer que os dados foram salvos se não foram.', 'Relaciono as três partes e comparo duas mensagens de erro.'),
    slide('Investigue antes de editar', 1, 15, 'O fluxo funciona. As mensagens deixam dúvidas: encontre três.', [['1 · Campo vazio', 'Tente enviar sem escolher um campeonato.'], ['2 · Sucesso', 'Escolha Xadrez rápido e envie.'], ['3 · Cancelamento', 'Abra Cancelar inscrição. Primeiro volte; depois confirme.']], 'Em Investigar e decidir, registre: mensagem → dúvida → consequência.', 'Confiro três problemas diferentes. Exemplos: “Aguarde” não explica a espera; “Pronto” não confirma o resultado; “Tem certeza?” não explica o que será desfeito. Mostro falha de conexão e nova tentativa. O comportamento funciona de propósito: o problema está no texto.', '2 min: modelo um diagnóstico; 8 min: exploração individual; 5 min: três registros e conferência.', {resources: [workshop]}),
    slide('Guarde o ponto de partida', 1, 7, 'Crie a pasta Aula-11. Ela vai guardar sua entrega.', [['Salvar versão inicial', 'Baixe projeto-inicial.interacao. Preserve o diagnóstico.'], ['Antes de sair', 'Confira o arquivo. Retomada às 20:05.']], 'O exemplo pronto funciona mesmo sem seus arquivos antigos.', 'Mostro o download e a pasta real. Confiro três problemas registrados. Não sobrescrever projeto-inicial.interacao ao salvar a versão final; o rascunho é apenas apoio.', 'Criação da pasta, primeiro salvamento e conferência.'),
    slide('Intervalo', 1, 20, 'Lanche das 19:45 às 20:05.', [], 'Retorne ao mesmo posto com o projeto salvo.', 'O intervalo fica fora dos 170 minutos de atividade.', 'Intervalo.', {pace: 'break'}),
    slide('Retomada: só conclua o que falta', 2, 5, 'Os seis desafios são aquecimento. Quem terminou não repete.', [['Falta um?', 'Abra somente a cena que ainda não foi testada.'], ['Terminou?', 'Salve e prepare a nova aba do criador.']], 'Não abra outro contador nem reescreva uma frase pronta.', 'Faço chamada e confirmo que esta parte fecha o aquecimento. Demonstro uma cena apenas para quem ainda precisa; quem já fez os seis preserva seu trabalho.', '2 min: chamada; 3 min: concluir apenas pendências.', {resources: [workshop]}),
    slide('Acompanhe a inscrição acontecer', 2, 5, 'Se faltar uma cena, teste o caminho completo uma vez.', [['Espera', 'Veja o envio acontecer.'], ['Sucesso', 'Confira se o resultado aparece.']], 'Terminou os seis? Salve. Não crie outra versão agora.', 'Não há nova rodada de textos. A turma usa estes minutos para fechar pendências reais e salvar, sem perder tempo repetindo o que já está concluído.', '5 min: pendência, percurso ou salvamento.'),
    slide('Faça o erro ajudar a pessoa', 2, 5, 'Use este tempo apenas se ainda falta testar uma recuperação.', [['Falha', 'Tente novamente sem perder a escolha.'], ['Cancelamento', 'Mantenha ou confirme e comece de novo.']], 'Quem concluiu pode abrir a pasta e conferir o salvamento.', 'Oriento pontualmente quem está em uma cena incompleta. O restante não ganha tarefa extra de escrita.', '5 min: pendências individuais.'),
    slide('Feche o aquecimento', 2, 5, 'Salve o que já fez. A próxima atividade é outra criação.', [['Guardar', 'Mantenha seu projeto anterior.'], ['Preparar', 'Deixe uma nova aba livre para o criador.']], 'Às 20:30, pare nos seis desafios mesmo que tenha terminado antes.', 'Aviso que o próximo trabalho não é sobre melhorar as mesmas frases. Ele usa escolhas, rotas e uma mudança de requisito.', '3 min: salvar; 2 min: preparar a nova aba.'),
    slide('Seis desafios, aquecimento concluído', 2, 5, 'Não conte de novo. Não refaça. Agora você vai criar telas e conexões próprias.', [['O que fica', 'Seu projeto de interações continua salvo.'], ['O que muda', 'No próximo slide, abre o Criador de fluxos.']], 'Se já terminou, salve seu projeto e prepare uma nova aba para o criador.', 'Faço a transição visual: as seis mensagens foram uma prática de observar resposta; a próxima etapa usa o mesmo cuidado em um fluxo criado do zero.', '5 min: síntese curta e preparação para o slide 13.'),
    slide('20:30 · Agora crie um fluxo seu', 3, 25, 'Abra o Criador de fluxos, escolha um briefing e construa o caminho principal.', [['Escolha um briefing', 'Reserva de estúdio, empréstimo de equipamento ou pedido de lanche.'], ['Cinco telas', 'Início → Escolha → Revisão → Concluído; Ajuda entra quando a pessoa precisa.'], ['Ligue e teste', 'Cada botão leva a uma tela. A escolha aparece na revisão e na conclusão.']], 'Em 25 minutos, faça o caminho principal funcionar antes de enfeitar qualquer tela.', 'No projetor digo em 10 segundos: “Abram o Criador, escolham um briefing e façam o caminho funcionar.” Mostro somente a primeira conexão. Libero imediatamente: cada estudante decide títulos, textos, botões e destinos. Confirmo que o criador permite até oito telas. Não é para refazer os seis desafios, nem escrever código.', '3 min: mostrar o briefing e a primeira conexão; 17 min: criação individual das cinco telas; 5 min: testar início até concluído.', {resources: [creator]}),
    slide('Mudança do cliente: uma opção ficou indisponível', 3, 20, 'Clique em Receber nova exigência. Sem apagar o caminho que funciona, adicione e conecte uma sexta tela de alternativa.', [['Revele', 'O pedido mostra qual opção não pode mais ser escolhida.'], ['Crie e ligue', 'Use + Adicionar tela; conecte a opção indisponível à alternativa e a alternativa de volta à Escolha.'], ['Teste os dois lados', 'A opção disponível ainda conclui; a indisponível encontra ajuda.']], 'Mostre dois percursos: opção disponível → concluído; opção indisponível → alternativa → escolha.', 'Anuncio a mudança depois de o caminho principal existir. O pedido só revela a situação: cada estudante cria a sexta tela e define as conexões. Não aceito trocar apenas texto de botão. Quem precisar pode adicionar até oito telas, mas seis bem conectadas bastam.', '2 min: revelar a mudança; 13 min: criar alternativa e rotas; 5 min: testar os dois percursos.'),
    slide('Feche o teste com o colega', 4, 5, 'Uma observação oral basta. Corrija a rota se ele parou.', [['Conseguiu', 'Siga para o slide 16.'], ['Parou', 'Ajuste botão, destino ou tela e teste uma vez.']], 'Não abra relatório nem repita toda a troca.', 'Fecho a atividade de colega em cinco minutos. Quem já tem a rota validada abre diretamente o slide 16 às 21:20.', '2 min: terminar a segunda tentativa; 3 min: ajuste pontual.'),
    slide('21:20 · Dê cara de app', 4, 10, 'No Criador, abra a missão 1. Antes de atualizar a página, use Salvar rascunho; depois escolha tema, nome e raio.', [['Tema', 'Studio, Arcade ou Editorial.'], ['Nome', 'Dê um nome que combine com seu briefing.'], ['Raio', 'Ajuste os cantos e veja o resultado na prévia.']], 'Escolha e veja a tela mudar. Não redesenhe todas as telas.', 'Peço Salvar rascunho antes da atualização. Mostro uma escolha em poucos segundos e libero. A aparência deve servir ao fluxo: mesma cara nas telas, sem trocar conteúdo ou rotas agora.', '2 min: salvar e demonstrar; 8 min: escolha individual e conferência na prévia.', {resources: [creator]}),
    slide('21:30 · Formulário que funciona', 4, 15, 'Abra a missão 2. Selecione Início, crie um campo e ligue a resposta ao próximo passo.', [['Campo', 'Defina rótulo, dica e se é obrigatório. Um campo basta.'], ['Vazio', 'Envie sem responder e veja o erro na própria tela.'], ['Preenchido', 'Envie com resposta e mostre `{{resposta}}` na mensagem seguinte.']], 'Teste vazio e preenchido. A mesma tela precisa explicar como continuar.', 'Demonstro somente Início vazio → erro em linha → preenchido → resposta na tela seguinte. O vazio bloqueia o avanço. Uso uma resposta fictícia e libero; a tela 7 fica para a falha, se precisar.', '3 min: demonstração; 9 min: construir e ligar; 3 min: testar vazio e preenchido.'),
    slide('21:45 · A rede caiu', 4, 15, 'Abra a missão 3. Na Revisão, abra Carregamento e falha dos botões e configure o botão de confirmação.', [['Aguardar', 'Marque Aguardar no botão de confirmação: ele mostra que está trabalhando por um instante.'], ['Falha', 'Mantenha Vai para → Concluído e escolha Erro em Destino se falhar.'], ['Recuperar', 'Na tela Erro, Tentar de novo volta à Revisão; Cancelar espera mantém a pessoa na tela.']], 'No Criador, mostre falha e rede ok. Se criar tela Erro, conecte Tentar de novo à Revisão.', 'No painel Carregamento e falha dos botões, marco Aguardar no botão de confirmação, preservo o Vai para normal e escolho a rota Erro para a falha. No Criador, ativo Simular falha, confirmo e cancelo a espera; confirmo de novo e aguardo chegar a Erro. Desligo a falha, uso Tentar de novo para voltar à Revisão, confirmo e concluo. A tela 7 pode explicar o erro; a tela 8 só entra se for necessária. O protótipo exportado demonstra espera e caminho normal, não a simulação de falha.', '3 min: demonstrar falha; 8 min: configurar; 4 min: falha, cancelar, retry e rede ok.'),
    slide('22:00 · Speedrun e salvar', 4, 5, 'Abra a missão 4: resolva seu fluxo em até oito cliques. Depois salve.', [['Rodada', 'Faça o caminho até a confirmação.'], ['Compare', 'Veja quantos cliques usou antes e depois.'], ['Guardar', 'Salvar rascunho e Exportar protótipo.']], 'Se passou de oito, corte um desvio ou deixe o botão mais direto e tente outra vez.', 'Recomeçar teste limpa apenas a rodada: não apaga telas nem textos. O contador mostra o percurso para comparar tentativas, não dá nota. Quem já conseguiu usa Tab e Enter no protótipo exportado para conferir o foco.', '3 min: speedrun e ajuste; 2 min: salvar e exportar.'),
    slide('22:05 · Guarde e organize', 4, 5, 'Confira os dois arquivos e deixe o posto pronto para sair.', [['Pasta Aula-11', 'meu-fluxo.fluxo e meu-prototipo.html.'], ['Fechamento', 'Tema, formulário, recuperação e rota final funcionam.']], 'Mostre uma rota concreta se eu passar no seu posto.', 'Não estendo a oficina com outra tarefa. Confiro uma rota por tela, dois arquivos e organização; conecto a melhoria ao próximo encontro sobre experiência de uso.', '5 min: arquivos, organização e saída.')
  ]
};
