// One source for the planning, projected lesson and generated course assets.
const times = ['19:00 - 19:45', '20:05 - 20:50', '20:50 - 21:30', '21:30 - 22:10'];
const blocks = [
  'Descobrir as colunas escondidas em telas conhecidas (streaming, loja e rede social), entender coluna, espaço entre colunas e margem, e experimentar a oficina de grade. Salvar o projeto antes do lanche.',
  'Montar individualmente a página da Arena Pixel, casa de games fictícia, numa grade de 12 colunas: cabeçalho, destaque, três cartões de campeonato e botão. Reconhecer componentes que se repetem. Exportar a versão 1.',
  'Atender ao pedido do cliente: incluir um quarto campeonato e reorganizar os cartões com a mesma largura, sem sair da grade. Testar a leitura e exportar a página final.',
  'Criar um post quadrado para a mesma marca numa grade de 6 colunas, com os mesmos componentes da página. Comparar as duas peças, salvar, reabrir e escrever uma frase sobre a grade. Encerrar às 22:10.'
];
export const planning = {
  title: 'Grades e Sistemas Visuais',
  description: 'Monte a página de uma casa de games numa grade de 12 colunas e crie um post da mesma família visual.',
  objectives: ['Desenvolvimento do Projeto: leiaute, templates e equilíbrio visual.'],
  technical: ['Aplicar procedimentos técnicos de diagramação, proximidade e alinhamento.', 'Aplicar estilos css (cascading style sheets) para desenvolvimento de design web.'],
  socio: ['Demonstrar espírito colaborativo em atividades coletivas.'],
  blocks, times,
  methodology: 'Descoberta visual com telas projetadas, jogo rápido de contagem de colunas, demonstração curta e produção individual em etapas na oficina de grade, com alteração de pedido do cliente e adaptação para post. Conferência automática da oficina e comparação com o colega do lado, cada um no seu posto.',
  resources: 'Computadores com navegador, projetor, caderno e caneta. Oficina de grade local e gratuita, sem instalação, cadastro ou dependências externas. Sem impressão e sem fichas. Baixar a oficina antes do encontro permite uso sem internet.',
  observation: '19:00–22:10, com lanche 19:45–20:05. Chamada às 19:00, 20:05, 20:50 e 21:30. Trabalho individual no posto; a colaboração acontece na conferência com o colega do lado, sem circulação. Se houver computador compartilhado, alternar o operador a cada etapa e manter uma frase por aluno. Sem internet: abrir a oficina previamente baixada. Sem computador: desenhar no caderno uma faixa de 12 colunas e montar a página e o post com retângulos, seguindo os mesmos critérios. A grade é trabalhada de forma visual; nenhum aluno escreve código. Câmeras e ring lights não são necessárias.'
};
export const lesson = {...planning, socioemotional: planning.socio, schedule: times.map((horario, i) => ({horario, atividade: blocks[i]}))};
delete lesson.blocks;
delete lesson.times;
delete lesson.socio;
export const visualAlt = {
  telas: 'Esboços de um streaming, de uma loja online e de uma rede social no celular',
  'telas-grade': 'Os mesmos esboços com as colunas marcadas em rosa: 12 colunas no streaming e na loja, 4 no celular',
  doze: 'Doze colunas divididas em 2 itens de 6, 3 de 4, 4 de 3 e 6 de 2',
  'pagina-inicial': 'Página da Arena Pixel com itens de larguras diferentes e desalinhados',
  'pagina-final-exemplo': 'Página da Arena Pixel com quatro cartões iguais encaixados na grade',
  'post-exemplo': 'Post quadrado da Arena Pixel com marca, destaque, cartão e botão na grade de 6 colunas'
};
const card = (title, text) => ({title, text});
const teacher = (speech, steps, watch, rescue = 'Se alguém travar, demonstrar um único movimento na oficina e devolver o controle ao aluno no posto.') => ({speech, steps, watch, rescue});
const slide = (title, block, lede, details, notes) => ({title, block, lede, layout: 'dw8', ...details, ...(details.visual ? {visualAlt: [details.visual].flat().map(name => visualAlt[name])} : {}), teacher: notes});
const editor = {href: 'modelos/design-web/aula-08/oficina.html', label: 'Abrir a oficina de grade'};
export const support = {
  appendDefaultClosing: false,
  teacherGoal: 'Cada estudante entrega a página da Arena Pixel na grade (versão 1 e final com quatro cartões iguais), o post quadrado da mesma família e o projeto editável reaberto até 22:10.',
  routine: ['Antes da aula, abrir a apresentação e baixar a oficina em cada computador; testar uma exportação e a reabertura do projeto.', 'Manter os alunos no posto; pedir atenção antes de cada demonstração e liberar só a etapa indicada.'],
  onlineRoutine: 'A oficina não usa serviços externos. Uma cópia baixada do HTML abre o mesmo recurso sem internet, por duplo clique.',
  plainLanguage: 'Grade é um conjunto de colunas invisíveis que organiza a tela. Componente é uma peça que se repete sempre igual, como um cartão ou um botão. Um conjunto de componentes que combinam forma um sistema visual, e é ele que faz peças diferentes parecerem da mesma marca.',
  say: 'Toda tela que vocês usam tem colunas escondidas. Hoje vamos encontrar essas colunas e usar uma grade para montar uma página e um post da mesma marca.',
  demo: ['Revelar as colunas em três telas conhecidas.', 'Arrastar um cartão na oficina e mostrar que ele gruda na coluna.', 'Mudar a largura de um cartão com Mais estreito e Mais largo.', 'Exportar um PNG, salvar e reabrir o projeto.'],
  studentDeliverable: 'Pasta Aula-08: pagina-v1.png, pagina-final.png, post-final.png e projeto.grade. No caderno, uma frase sobre o uso da grade. Alternativa: página e post desenhados no caderno sobre uma faixa de 12 colunas.',
  check: ['Todos os itens começam e terminam numa coluna.', 'Nada passa da margem nem fica sobreposto.', 'Os quatro cartões da página final têm a mesma largura.', 'O post usa a mesma marca, o mesmo cartão e o mesmo botão da página.', 'Os três PNGs e o projeto editável foram salvos e reabertos.'],
  fallback: 'Abrir a cópia da oficina baixada antes da aula. Se o computador falhar, desenhar no caderno uma faixa de 12 colunas e montar a página com retângulos (cabeçalho, destaque, quatro cartões e botão); depois, um quadrado de 6 colunas para o post. Os critérios são os mesmos. Não distribuir fichas.',
  extension: 'Depois de salvar a entrega, criar pagina-alternativa.png com outra organização que também passe na conferência, e comparar qual deixa os horários mais fáceis de achar. Permanecer no posto até o encerramento.',
  commonProblems: [
    ['O aluno quer trocar cor ou letra', 'A oficina não permite, de propósito: hoje o desafio é posição e largura. Lembrar que as peças precisam parecer da mesma família.'],
    ['O cartão novo fica maior para destacar', 'Perguntar se ele ainda parece irmão dos outros. No sistema, todo campeonato usa o mesmo cartão.'],
    ['Falta tempo', 'Priorizar a página final com quatro cartões e o post. Reservar os últimos 12 minutos para exportar, salvar e reabrir.']
  ],
  presentationSlides: [
    slide('Mapa da noite', 1, 'Uma casa de games, uma grade de 12 colunas e duas peças da mesma família.', {cards: [card('Descobrir a grade', '19:00 às 19:45 · colunas escondidas em telas que você conhece.'), card('Montar a página', '20:05 às 20:50 · tudo encaixado na grade.'), card('Atender o cliente', '20:50 às 21:30 · um campeonato novo entra na página.'), card('Criar o post', '21:30 às 22:10 · mesma família, outro formato.')], promptLabel: 'Pausa', prompt: 'Lanche das 19:45 às 20:05. Encerramento às 22:10.'}, teacher('Hoje ninguém escolhe cor nem letra: elas já estão prontas. O desafio é encaixar tudo numa grade e fazer duas peças que pareçam irmãs.', ['3 min · Fazer chamada e apresentar o produto da noite.', '2 min · Combinar posto fixo, voz baixa e mão levantada para pedir ajuda.'], 'Todos no próprio posto, sem formar grupos.')),
    slide('Tem uma grade escondida', 1, 'Três telas que você usa toda semana. Repare no que se repete.', {visual: 'telas', promptLabel: 'Observe', prompt: 'O que aparece várias vezes, sempre com o mesmo tamanho, em cada tela?'}, teacher('Não diga ainda que existe uma grade. Deixe a turma perceber a repetição sozinha.', ['2 min · Leitura silenciosa das três telas.', '4 min · Ouvir respostas: capas iguais, produtos iguais, posts iguais.', '1 min · Perguntar: por que alguém faria tudo do mesmo tamanho?'], 'Respostas que citam um elemento concreto: capa, produto, post, botão.')),
    slide('Agora com as colunas', 1, 'As faixas cor-de-rosa são colunas. Quase tudo começa e termina numa delas.', {visual: 'telas-grade', promptLabel: 'Desafio rápido', prompt: 'Quantas colunas ocupa uma capa do streaming? E um produto da loja?'}, teacher('Revele as colunas e peça que contem com o dedo, sem levantar.', ['2 min · Mostrar as colunas e dar tempo para contar.', '3 min · Ouvir palpites.', '3 min · Conferir: a capa do streaming ocupa 2 das 12 colunas; o produto da loja ocupa 3 das 12; o post do celular ocupa as 4 colunas.'], 'Resposta certa: 2 colunas para a capa e 3 para o produto. Vale explicação informal, desde que a contagem esteja certa.')),
    slide('As linhas invisíveis', 1, 'Grade é o esqueleto da tela: quem usa não vê, mas sente a organização.', {cards: [card('Coluna', 'Faixa onde os itens se apoiam. Um item pode ocupar uma ou várias.'), card('Espaço entre colunas', 'O respiro que impede um item de encostar no outro.'), card('Margem', 'A borda livre em volta da tela. Nada encosta nela.')], promptLabel: 'Resumo', prompt: 'Na grade, cada item começa numa coluna e termina numa coluna.'}, teacher('Aponte cada termo nas telas do slide anterior. Os nomes em português bastam; não é preciso termo técnico em inglês.', ['3 min · Explicar coluna e espaço entre colunas voltando às capas do streaming.', '2 min · Mostrar a margem da loja.', '2 min · Pedir que um aluno diga, do lugar, onde começa e onde termina um produto.'], 'A turma usa as palavras coluna, espaço e margem para descrever uma tela.')),
    slide('Por que 12 colunas?', 1, '12 se divide de vários jeitos. Por isso tantos sites usam essa grade.', {visual: 'doze', promptLabel: 'Pense rápido', prompt: 'Se a página tiver quatro cartões lado a lado, quantas colunas cada um ocupa?'}, teacher('Leia o slide como um jogo de divisão, sem conta no quadro.', ['2 min · Mostrar as quatro divisões.', '3 min · Ouvir a resposta do desafio: 3 colunas, porque 12 dividido por 4 dá 3.'], 'A resposta 3 volta mais tarde, quando o cliente pedir um cartão novo. Não antecipe esse pedido.')),
    slide('Experimente a oficina', 1, 'Abra a oficina da aula. Textos, cores e letras já estão prontos.', {cards: [card('1 · Crie a pasta', 'Crie uma pasta Aula-08 para guardar tudo de hoje.'), card('2 · Arraste um cartão', 'Com Mostrar colunas ligado, arraste um cartão. Ele gruda na coluna mais próxima.'), card('3 · Mude a largura', 'Use Mais estreito e Mais largo e veja quantas colunas o cartão ocupa.')], resources: [editor], promptLabel: 'Antes do lanche', prompt: 'Clique em Salvar projeto e guarde projeto.grade na pasta Aula-08.'}, teacher('Abra a oficina pelo link e mostre arrastar, mudar a largura, usar as setas e desfazer. Ninguém digita número nem código.', ['4 min · Demonstrar arrastar, mudar a largura e desfazer.', '5 min · Cada aluno experimenta com um cartão.', '4 min · Conferir o download de projeto.grade na pasta Aula-08.'], 'Onde o navegador guardou o arquivo. Resolva agora, não no fim da aula.', 'Se o link não abrir, usar a cópia baixada antes da aula. Sem computador, desenhar no caderno uma faixa com 12 colunas e marcar três cartões de 4 colunas.')),
    slide('Intervalo', 1, 'Lanche. Retome no mesmo posto às 20:05.', {pace: 'break', promptLabel: 'Antes de sair', prompt: 'Deixe o projeto salvo. Comida e bebida longe dos computadores.'}, teacher('O intervalo fica fora dos 170 minutos de atividade.', ['20 min · Intervalo das 19:45 às 20:05.'], 'Retomar sem reorganizar a sala.')),
    slide('O pedido da Arena Pixel', 2, 'Uma casa de games fictícia quer divulgar os campeonatos. A página chegou assim.', {visual: 'pagina-inicial', promptLabel: 'Missão individual', prompt: 'Coloque tudo na grade. Não mude textos nem cores: só posição e largura.'}, teacher('Faça a chamada. Pergunte o que está estranho antes de abrir a oficina.', ['2 min · Fazer chamada e retomar o projeto.', '3 min · Apresentar o pedido.', '3 min · Ouvir os problemas: cartões de larguras diferentes, começos desalinhados, cabeçalho e rodapé passando da margem.'], 'As críticas apontam o elemento, não quem fez a página.')),
    slide('Monte na grade', 2, 'Continue na oficina, na aba Página. Encaixe item por item.', {cards: [card('Topo', 'Cabeçalho e destaque ocupando a largura toda.'), card('Cartões', 'Os três lado a lado, com a mesma largura.'), card('Ação', 'Botão abaixo dos cartões, começando numa coluna.')], promptLabel: 'Conferência da oficina', prompt: 'O quadro Conferência marca ✓ quando está tudo na grade, dentro da margem e sem nada sobreposto.'}, teacher('Demonstre só o cabeçalho. O resto é com eles.', ['3 min · Demonstrar o cabeçalho ocupando as 12 colunas.', '14 min · Montagem individual.', '3 min · Atender quem levantou a mão.'], 'Três cartões de 4 colunas é o caminho mais comum, mas outra solução que passe na conferência também vale.')),
    slide('Peças que se repetem', 2, 'Quando uma peça aparece sempre igual, ela vira componente.', {cards: [card('Cartão', 'Todo campeonato usa o mesmo cartão. Muda o texto, o desenho fica.'), card('Botão', 'Toda ação importante usa o mesmo botão.'), card('Cabeçalho', 'Toda página da Arena começa igual.')], promptLabel: 'Sistema visual', prompt: 'Componentes que combinam entre si formam um sistema visual. É ele que dá a várias peças a cara da mesma marca.'}, teacher('Volte às capas do streaming: cada capa é um componente repetido.', ['3 min · Explicar componente usando o cartão da oficina.', '2 min · Pedir exemplos de componentes em apps que a turma usa.', '2 min · Ligar componente e grade: o componente sempre ocupa colunas inteiras.'], 'Exemplos que a turma pode citar: botão de curtir, cartão de produto, miniatura de vídeo.')),
    slide('Versão 1', 2, 'Afaste-se um pouco da tela, sem levantar, e responda para você mesmo.', {bullets: ['Os três cartões parecem irmãos?', 'Os começos dos itens formam linhas retas?', 'O espaço entre os cartões é igual?'], promptLabel: 'Salve a versão 1', prompt: 'Com a conferência toda em ✓, escolha pagina-v1.png em Nome da imagem, clique em Exportar PNG e salve projeto.grade.'}, teacher('O teste é visual e rápido. Corrigir uma coisa e salvar.', ['3 min · Fazer o teste de olhar de longe.', '4 min · Corrigir um ponto.', '3 min · Exportar pagina-v1.png e salvar o projeto.'], 'Quem terminou cria uma alternativa com o botão em outra coluna, sem sair da grade.')),
    slide('Chegou um campeonato novo', 3, 'O cliente quer anunciar mais um campeonato na página.', {cards: [card('Novo cartão', 'Xadrez rápido · Sábado · 15h'), card('Condição', 'Os quatro cartões ficam lado a lado, com a mesma largura.'), card('Regra', 'Nada sai da grade nem das margens.')], promptLabel: 'Pedido do cliente', prompt: 'Clique em Incluir campeonato novo. Antes de mexer: quantas colunas cada cartão vai ocupar?'}, teacher('Faça a chamada e anuncie o pedido como se fosse o cliente.', ['2 min · Fazer chamada.', '3 min · Apresentar o pedido.', '3 min · Ouvir palpites. Resposta: 3 colunas cada, porque 12 dividido por 4 dá 3. É o desafio do início da aula.'], 'Quem lembrar do desafio das 12 colunas explica para a turma em uma frase.')),
    slide('Reorganize os cartões', 3, 'O cartão novo precisa caber na mesma linha, sem empurrar nada para fora.', {cards: [card('1 · Estreite', 'Deixe os três cartões antigos com 3 colunas.'), card('2 · Encaixe', 'Coloque o Xadrez rápido na mesma linha dos outros.'), card('3 · Confira', 'Veja se o botão e o rodapé continuam livres e na grade.')], promptLabel: 'Pronto quando', prompt: 'Quatro cartões iguais, lado a lado, e a conferência toda em ✓.'}, teacher('Mostre só como estreitar um cartão. Não monte a linha inteira.', ['3 min · Demonstrar Mais estreito em um cartão.', '14 min · Reorganização individual.', '3 min · Atender quem pedir ajuda.'], 'O cartão novo tem o mesmo desenho dos outros. Se alguém tentar deixá-lo maior para destacar, perguntar se ainda parece da mesma família.')),
    slide('Teste de leitura', 3, 'Olhe para a sua página sem apontar com o mouse.', {bullets: ['Qual campeonato acontece no sábado?', 'Onde eu clico para participar?', 'Algum cartão parece de outra família?'], promptLabel: 'Versão final da página', prompt: 'Corrija o que atrapalhou. Escolha pagina-final.png, exporte e salve projeto.grade.'}, teacher('Cada um testa a própria tela. O colega do lado pode responder do lugar dele, se quiser.', ['3 min · Fazer as três perguntas.', '5 min · Corrigir.', '4 min · Exportar pagina-final.png e salvar o projeto.'], 'O PNG final tem os quatro cartões.')),
    slide('Agora o post', 4, 'A Arena quer anunciar o xadrez no feed. O post precisa ter a cara da mesma marca.', {cards: [card('Mesma marca', 'O nome e o ícone da Arena no topo.'), card('Mesmo cartão', 'O Xadrez rápido com o mesmo desenho da página.'), card('Mesmo botão', 'Quero participar, igualzinho.')], promptLabel: 'Nova grade', prompt: 'Abra a aba Post quadrado. Aqui a grade tem 6 colunas.'}, teacher('Faça a chamada. Mostre que o formato mudou e a família não.', ['2 min · Fazer chamada.', '3 min · Apresentar o post.', '3 min · Abrir a aba e mostrar as 6 colunas.'], 'Ninguém troca cor ou letra do post: a oficina não permite, e isso é de propósito.')),
    slide('Monte o post', 4, 'Os componentes são os mesmos. Só a grade mudou.', {cards: [card('1 · Topo', 'Marca no alto, começando na primeira coluna.'), card('2 · Meio', 'Destaque e cartão encaixados na grade de 6.'), card('3 · Ação', 'Botão perto do cartão, alinhado com ele.')], promptLabel: 'Pronto quando', prompt: 'Conferência em ✓. Escolha post-final.png, exporte e salve projeto.grade.'}, teacher('Demonstre só a marca. Deixe o resto com eles.', ['2 min · Demonstrar a marca na primeira coluna.', '12 min · Montagem individual do post.'], 'Botão e cartão lado a lado ou empilhados: os dois jeitos valem se estiverem na grade.')),
    slide('É da mesma família?', 4, 'Página e post lado a lado. Formatos diferentes, mesma marca.', {visual: ['pagina-final-exemplo', 'post-exemplo'], promptLabel: 'Compare com as suas', prompt: 'Mesmas cores, mesmo cartão, mesmo botão e tudo em colunas?'}, teacher('Mostre o exemplo só depois que a turma montou o próprio post.', ['2 min · Mostrar página e post lado a lado.', '4 min · Cada aluno compara as próprias peças e corrige um detalhe; o colega do lado dá um palpite, do lugar.'], 'O exemplo é uma solução possível, não a única resposta.')),
    slide('Salve e reabra', 4, 'A entrega precisa abrir fora da oficina e permitir continuar a edição.', {cards: [card('1 · Imagens', 'pagina-v1.png, pagina-final.png e post-final.png.'), card('2 · Projeto', 'Salvar projeto → projeto.grade.'), card('3 · Teste', 'Abra um PNG. Depois use Abrir projeto e confira a página e o post.')], promptLabel: 'Pasta Aula-08', prompt: 'pagina-v1.png + pagina-final.png + post-final.png + projeto.grade'}, teacher('O navegador pode colocar números nos nomes repetidos. Guarde a versão mais recente.', ['3 min · Exportar o que faltar e salvar o projeto.', '3 min · Reabrir e conferir as duas abas.', '1 min · Organizar a pasta Aula-08.'], 'PNG é só imagem: sem projeto.grade não dá para continuar editando.', 'Se o download falhar, tentar de novo e olhar a pasta Downloads. Persistindo, tirar captura de tela e escrever a conclusão no caderno; não considerar o projeto entregue sem conferir o arquivo.')),
    slide('Uma frase de designer', 4, 'No caderno, complete a frase com algo que você fez hoje.', {promptLabel: 'Sua frase', prompt: '“Usei a grade para ___ e isso ajudou ___.”', bullets: ['Exemplo: “Usei a grade para deixar os quatro cartões com a mesma largura e isso ajudou a comparar os horários.”', 'Pasta salva e posto organizado antes de sair.']}, teacher('Ouça duas frases e feche retomando grade, componente e sistema visual.', ['2 min · Escrever a frase no caderno.', '2 min · Ouvir duas respostas.', '1 min · Organizar os postos e encerrar às 22:10.'], 'Sem apresentações longas no encerramento.'))
  ]
};
